FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

COPY dilemma/Dilemma/*.csproj ./
COPY common/dotnet/*.csproj ./
RUN dotnet restore

COPY dilemma/ dilemma/
COPY common/ common/

RUN dotnet publish "/app/dilemma/Dilemma/DilemmaSvc.WebApi" -c Release -o out 

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS final
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet", "DilemmaSvc.WebApi.dll"]