FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

COPY voting/Voting/*.csproj ./
COPY common/dotnet/*.csproj ./
RUN dotnet restore

COPY voting/ voting/
COPY common/ common/

RUN dotnet publish "/app/voting/Voting/VotingSvc.WebApi" -c Release -o out 

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS final
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet", "VotingSvc.WebApi.dll"]