version: '3.8'

services:
  rabbitmq:
    hostname: messagebus
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq

volumes:
  rabbitmq-data:
  rabbitmq-logs:
