version: '3.8'

services:
  api:
    build: ./Dilemma/DilemmaSvc.WebApi
    ports: 
      - 80:80
      - 443:443

  database:
    image: 'postgres'
    env_file:
      - database.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '25522:5432'
volumes:
  db-data: