version: '3.8'

services:
  database:
    image: 'postgres'
    env_file:
      - database.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '25522:5432'

  message_bus:
    image: 'rabbitmq'
    container_name: 'rabbitmq-messagebus'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  db-data:
  rabbitmq-data:
  rabbitmq-log: