version: '3.8'

services:
  database:
    image: 'postgres'
    env_file:
      - database.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '25522:5432'

volumes:
  db-data:
